//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.19 at 12:57:34 PM BRT 
//


package develdio.com.oneagentweb.plataform;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the develdio.com.oneagentweb.plataform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: develdio.com.oneagentweb.plataform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OneAgentWebService01 }
     * 
     */
    public OneAgentWebService01 createOneAgentWebService01() {
        return new OneAgentWebService01();
    }

    /**
     * Create an instance of {@link OneAgentWebService01 .Input }
     * 
     */
    public OneAgentWebService01 .Input createOneAgentWebService01Input() {
        return new OneAgentWebService01 .Input();
    }

}
